### ISSUE TITLE
Switch app framework from Play!(Java) to DJango(Python):

### ISSUE THREAD

**Issue by zhassler** [Grasslands-2/GrazeScapeServer#5]
Clone current GrazeScape repo into a new repo and use that to switch the framework structure from Play to Django.  Keep in mind that we will have to keep a Java server active in this new frame work to handle current map, and model functions.

**Comment by mmbayles** [comment]
I have successfully created a new repo and have made significant progress in switching frameworks. The Django server is setup and running. There are a couple of more issues to sort out with Extjs in order to get the app running properly.

**Comment by mmbayles** [comment]
The django app appears to be at the same level of functionality as the play app.
